### ISSUE TITLE
domain 구현

### ISSUE THREAD

**Issue by bo1030** [bo1030/taxi_sharing#16]

**Comment by kjw6867** [comment]
채팅룸 도메인 구현했습니다.

**Comment by kjw6867** [comment]
채팅룸 메시지 도메인, 채팅룸 참여자 도메인 추가했습니다.

**Comment by kjw6867** [comment]
도메인 일부 수정했습니다

**Comment by bo1030** [comment]
### 

> 도메인 일부 수정했습니다

확인했습니다.

**Comment by DooooH** [comment]
https://yh0921k.tistory.com/23 (util.Date vs sql.Date)
domain Date 구성 시 사용하는 java.util.Date 는 사용을 권고하지 않는다고 하네요 mutable 클래스라 그런 것 같네요
sql.date 는 시-분-초가 들어가지 않아서 사용하기 어려울 것 같고 java.time의 클래스를 사용하면 된다고 하는데 조금 더 알아볼게요
(참고: https://footprint-of-nawin.tistory.com/67,  https://madplay.github.io/post/reasons-why-javas-date-and-calendar-was-bad)

**Comment by kjw6867** [comment]
> https://yh0921k.tistory.com/23 (util.Date vs sql.Date) domain Date 구성 시 사용하는 java.util.Date 는 사용을 권고하지 않는다고 하네요 mutable 클래스라 그런 것 같네요 sql.date 는 시-분-초가 들어가지 않아서 사용하기 어려울 것 같고 java.time의 클래스를 사용하면 된다고 하는데 조금 더 알아볼게요 (참고: https://footprint-of-nawin.tistory.com/67, https://madplay.github.io/post/reasons-why-javas-date-and-calendar-was-bad)

알겠습니다. 감사합니다

**Comment by DooooH** [comment]
waiting-room 초기 도메인 추가했습니다

**Comment by bo1030** [comment]
> waiting-room 초기 도메인 추가했습니다

확인했습니다.

**Comment by ghost** [comment]
payment 도메인 추가했습니다.

**Comment by DooooH** [comment]
waiting-room domain 추가하였습니다.
