### ISSUE TITLE
DTO Request 쿼리 생성자 구현

### ISSUE THREAD

**Issue by DooooH** [bo1030/taxi_sharing#23]
```java
private String departure_time;
private String departure_address;
private String departure_latitude;
private String departure_longitude;
private String destination_address;
private String destination_latitude;
private String destination_longitude;
```

- 쿼리 요소들이 있을 수도 있고 없을 수도 있는데 생성자를 구현하는 방법 고민 필요
- 인자를 Optional로 구현하는 방법으로 고민중

**Comment by bo1030** [comment]
Optional이 깔끔하고 좋을것같습니다.

**Comment by DooooH** [comment]
https://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/
dto request에 우선 Optional을 적용했는데, intellij 에서 필드에 사용하니 경고가 떠서 알아보니 Optional 타입은 필드에 타입으로 선언할때 사용하지 않는다고 하네요.
링크에 5번항목 참고하시면 좋을 것 같습니다.
@bo1030 @huittting @kjw6867
